/*
 * Mastermind.cpp 
 * Mastermind game main funcion
 * Writter:  Cai Mingda
 * Date:     8 Nov, 2015
 */

#include <iostream>
#include "GamePlayer.h"
#include "GameController.h"

using namespace std;

int main()
{
    // Declare an opponent object
    GameController gamecontroller;
    // Declare a player object
    GamePlayer gameplayer;

    short i = 0;

    // Opponent generates a random number sequence
    gamecontroller.generateRnd();

    cout << "****************************************************\n";
    cout << "*                   Mastermind                     *\n";
    cout << "* Instructions:                                    *\n";
    cout << "* Guess the correct 4 interger number sequence     *\n";
    cout << "* generated by program. Each integer is between 1  *\n";
    cout << "* and 6. If the position and number are both       *\n";
    cout << "* correct, black pegs will plus one. If number is  *\n";
    cout << "* correct but position is wrong, white pegs will   *\n";
    cout << "* plus one. Player have only maximum 8 chances.    *\n";
    cout << "* Input numbers should be seperated by space, then *\n";
    cout << "* press enter. For example:                        *\n";
    cout << "* 1 2 3 4 <enter>                                  *\n";
    cout << "* Have fun!                                        *\n";
    cout << "****************************************************\n";

    for(i = 0; i < CHANCE_NUM; i++)
    {
        gameplayer.guessNumber();
        if(gamecontroller.checkResult(gameplayer.slot) == true)
        {
            cout << "\n\nYOU WIN! :)\n\n";
            break;
        }
    }
    
    if(i == CHANCE_NUM)
    {
        cout << "\n\nYOU LOSE! :(\n\n";
    }

}


